[package]
name = "zip_dict_attack"
version = "0.1.0"
edition = "2021"
authors = ["Raui Ghazaleh <rj.ghazaleh@gmail.com>"]
license = "MIT"

[dependencies]
rayon = "1.5.3"
zip = "0.6.2"
indicatif = {version = "*", features = ["rayon"]}
clap = { version = "4.0.13", features = ["derive"] }
